export class Addcentercontact {

    constructor(
        public centid: string = "",
        public centname: string = "",
        public premisesowner: string = "",
        public state: string = "",
        public district: string = "",
        public city: string = "",
        public address: string = "",
        public pinno: string = "",
        public contactno: string = "",
        public centstdt: Date = new Date(),
        public centenddt: Date = new Date(),
        public centeremail: string = "",
        public centerrent: number = 0,
        public remark: string = "",
        public pgid: string = "",
        public caldlls: string = "",
        public digitechcenterid: string = "",
        public principalname: string = "",
        public principalcontact: string = "",
        public principalemail: string = "",
        public centbillapplicable: string = "",
        public billremark: string = "",
        public gstapplicable: string = "",
        public gstno: string = "",
        public panno: string = "",
        public laptoptarget: number = 0,
        public region: string = "",
        public pcid: string = "",
        public ohid: string = "",
        public eteamleaderid: string = "",
        public engid: string = "",
        public placcoordinatorid: string = "",
        public iditeamleaderid: string = "",
        public teamleaderid: string = "",
        public entrepreneurid: string = "",
        public progassociate: string = "",
        public infrastatus: string = "",
        public infraremark: string = "",
        public status: number = 0,
        public createdate: Date = new Date(),
        public createby: string = "",
        public updatedon: Date = new Date(),
        public updatedby: string = "",
        public seqno: number = 0,
        
        public noofclient: number = 0,
        public noofservers: number = 0,
        public total: number = 0,
      
    ) { }

}
