export class Getempsalary {

    constructor(
        public  pgid :string="",
        public  pgname :string="",
        public  depid :string="",
        public  depname :string="",
        public  empid :string="",
        public  employeename :string="",
        public  emptype :string="",
        public active :number=0,
        public  desid :string="",
        public  installment :number=0.0,
        public balance :number=0.0,
        public loanstatus :number=0,
        public  loanid :string="",
        public loanamount :number=0.0,
        public grosssalary :number=0.0,
        public  absentday :number=0,
        public dayofmonth :number=0,
        public basicsal :number=0.0,
        public perday:number=0.0,
        public hra :number=0.0,
        public  ta :number=0,
        public oa :number=0.0,
        public absentamt :number=0.0,
        public epfamt :number=0.0,
        public esicamt :number=0.0,
        public tds :number=0.0,
        public  pt :number=0,
        public  telephone :number=0.0,
        public  advance :number=0.0,
        public  loan :number=0.0,
        public totdeduct :number=0.0,
        public netsalary :number=0.0,
        public epfamt2 :number=0.0,
        public esicamt2 :number=0.0,
        public ctc :number=0.0,
   
    ){}
}

