export class Salaryapprove {
    constructor(
        public  pgid :string="",
        public  pgname :string="",
        public  depid :string="",
        public  depname :string="",
        public  empid :string="",
        public  employeename :string="",
        public  emptype :string="",
        public active :number=0,
        public  desid :string="",
        public  installment :number=0.0,
        public balance :number=0.0,
        public loanstatus :number=0,
        public  loanid :string="",
        public loanamount :number=0.0,
        public finyear :string="",
        public  salmonth :string="",
        public salyear :string="",
        public prepareby :string="",
        public preparedate:number=0,
        public grosssalary :number=0.0,
        public  totaldeduct :number=0.0,
        public netamt :number=0.0,
        public ctcamt :number=0.0,
        public absent :number=0,
        public basicamt :number=0.0,
        public hraamt :number=0.0,
        public  taamt :number=0.0,
        public  oaamt :number=0.0,
        public  absamt :number=0.0,
        public  epfamt :number=0.0,
        public esic1 :number=0.0,
        public tds :number=0.0,
        public pt :number=0.0,
        public telephone :number=0.0,
        public advance :number=0.0,
        public loan :number=0.0,
        public cpfamt :number=0.0,
        public esic2 :number=0.0,
        public dayamt :number=0.0,
        public remark : string,
        public approve :number=0,
        
        public salstatus :number=0,
   
    ){}
}
